const ActionTypes ={
    UPDATE_CUSTOMERS : "UPDATE_CUSTOMERS",
    GET_CUSTOMERS :"GET_CUSTOMERS",
    ADD_CUSTOMERS:"ADD_CUSTOMERS",
    DEL_CUSTOMERS:"DEL_CUSTOMERS",
    GET_CUSTOMERS_SUCCEED:"GET_CUSTOMERS_SUCCEED",
    GET_CUSTOMERS_FAILED:"GET_CUSTOMERS_FAILED",
    ADD_CUSTOMERS_SUCCEED:"ADD_CUSTOMERS_SUCCEED",
    ADD_CUSTOMERS_FAILED:"ADD_CUSTOMERS_FAILED",
    UPDATE_CUSTOMERS_SUCCEED:"UPDATE_CUSTOMERS_SUCCEED",
    UPDATE_CUSTOMERS_FAILED:"UPDATE_CUSTOMERS_FAILED",
    DEL_CUSTOMERS_SUCCED:"DEL_CUSTOMERS_SUCCED",
    DEL_CUSTOMERS_FAILED:"DEL_CUSTOMERS_FAILED",
    // ini untuk auth
    LOGIN : "LOGIN",
    LOGIN_SUCCESSFUL : "LOGIN_SUCCESSFUL",
    LOGOUT : "LOGOUT",
    LOGIN_FAILED : "LOGIN_FAILED",
    TRY_AGAIN : "TRY_AGAIN",
    CONNECTION_ERROR : "CONNECTION_ERROR",
    VALIDATION_ERROR : "VALIDATION_ERROR",

}

export default ActionTypes